---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - JOBS=1 # https://github.com/emberjs/ember.js/issues/15641
  matrix:
    - EMBER_TRY_SCENARIO=ember-lts-2.4
    - EMBER_TRY_SCENARIO=ember-lts-2.8
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default
    #- EMBER_TRY_SCENARIO=fastboot-addon-tests

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm install -g yarn phantomjs-prebuilt
  - yarn --version
  - phantomjs --version

install:
  - yarn install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
